# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vern < Formula
  desc "16 AI personas, multi-LLM discovery pipelines, and VernHole councils. One idea in, battle-tested plan out."
  homepage "https://jdonohoo.github.io/vern-bot/"
  version "2.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jdonohoo/vern-bot/releases/download/v2.2.0/vern_darwin_amd64.tar.gz"
      sha256 "59859a2daa0ddf8e741034cad838be501d5a22b6eaf52022c1ba06e97fa070e4"

      def install
        bin.install "vern"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jdonohoo/vern-bot/releases/download/v2.2.0/vern_darwin_arm64.tar.gz"
      sha256 "eea64b26c8fc592ed273b4ca9e02e145fdb03fdf9151fc197510f5adf8ccf0b7"

      def install
        bin.install "vern"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdonohoo/vern-bot/releases/download/v2.2.0/vern_linux_amd64.tar.gz"
      sha256 "5d3eaec3b2e7d4f289ae9cae6a006cf247a65f7ab27daef91ce18b516cfcf3a5"
      def install
        bin.install "vern"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdonohoo/vern-bot/releases/download/v2.2.0/vern_linux_arm64.tar.gz"
      sha256 "ffaf022abd7024b6a0afa22687a5d91ef4c21bb97ecf4475e7cb0d9ba43e70b1"
      def install
        bin.install "vern"
      end
    end
  end

  test do
    system "#{bin}/vern", "--help"
  end
end
