# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vern < Formula
  desc "16 AI personas, multi-LLM discovery pipelines, and VernHole councils. One idea in, battle-tested plan out."
  homepage "https://jdonohoo.github.io/vern-bot/"
  version "2.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jdonohoo/vern-bot/releases/download/v2.1.0/vern_darwin_amd64.tar.gz"
      sha256 "c580cf2c847bd9113341999d285986b3ec48c1a73bfdc58aa0804a94357d8349"

      def install
        bin.install "vern"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jdonohoo/vern-bot/releases/download/v2.1.0/vern_darwin_arm64.tar.gz"
      sha256 "4effb678b842d3e09e5d3f91b7d04e5b1b0f668aa70761f33912c31f52607ca9"

      def install
        bin.install "vern"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdonohoo/vern-bot/releases/download/v2.1.0/vern_linux_amd64.tar.gz"
      sha256 "a8bb6c17b587297f83062a902fa941a51200754d31d5e76a832c5337bed08aa8"
      def install
        bin.install "vern"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdonohoo/vern-bot/releases/download/v2.1.0/vern_linux_arm64.tar.gz"
      sha256 "5754d27cd41b146d320c9cfa99a97a29a8699f068f1eab4e6a82aa9b6b899799"
      def install
        bin.install "vern"
      end
    end
  end

  test do
    system "#{bin}/vern", "--help"
  end
end
