# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vern < Formula
  desc "16 AI personas, multi-LLM discovery pipelines, and VernHole councils. One idea in, battle-tested plan out."
  homepage "https://jdonohoo.github.io/vern-bot/"
  version "2.7.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jdonohoo/vern-bot/releases/download/v2.7.0/vern_darwin_amd64.tar.gz"
      sha256 "d8ed4aad3625c5276513a411488d83564d1659f87a3c1415fdbe30865fb6bb50"

      def install
        bin.install "vern"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jdonohoo/vern-bot/releases/download/v2.7.0/vern_darwin_arm64.tar.gz"
      sha256 "532faa9ed3ce96188383f9e0436558fa5baba4e68e07f7ee8854821034415c5f"

      def install
        bin.install "vern"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdonohoo/vern-bot/releases/download/v2.7.0/vern_linux_amd64.tar.gz"
      sha256 "e7922c88b45bbb606570d6f91266db32ecb44c9c469e7f97f44825726062281d"
      def install
        bin.install "vern"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdonohoo/vern-bot/releases/download/v2.7.0/vern_linux_arm64.tar.gz"
      sha256 "4093c901dfdf9d5b8acdd7f81362a717e9d0b1e2ac715646d817b73de292f5bc"
      def install
        bin.install "vern"
      end
    end
  end

  test do
    system "#{bin}/vern", "--help"
  end
end
